In [43]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
#from NeuralMF import NeuralMF
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset
import pytorch_lightning as pl
import optuna
from sklearn.preprocessing import StandardScaler
from optuna.integration import PyTorchLightningPruningCallback
import gc  # 가비지 컬렉션
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [3]:
!pip install pytorch_lightning
!pip install optuna
!pip install optuna-integration[pytorch_lightning]

Collecting pytorch_lightning
  Downloading pytorch_lightning-2.5.1-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning) (2.6.0+cu124)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning) (4.67.1)
Requirement already satisfied: PyYAML>=5.4 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning) (6.0.2)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (2025.3.0)
Collecting torchmetrics>=0.7.0 (from pytorch_lightning)
  Downloading torchmetrics-1.7.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning) (24.2)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning) (4.12.2)
Collecting lightning-utilities>=0.10.0 (from pytorch_lightning)
  Downloading lightning_utilities-0.14.2-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2022.5.0->pytorch_lightning) (3.11.14)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from lightning-utilities>=0.10.0->pytorch_lightning) (75.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.1.0->pytorch_lightning)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1.0->pytorch_lightning) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.1.0->pytorch_lightning) (1.3.0)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.11/dist-packages (from torchmetrics>=0.7.0->pytorch_lightning) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (1.18.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.1.0->pytorch_lightning) (3.0.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning) (3.10)
Downloading pytorch_lightning-2.5.1-py3-none-any.whl (822 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.0/823.0 kB 26.6 MB/s eta 0:00:00
Downloading lightning_utilities-0.14.2-py3-none-any.whl (28 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 109.3 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 88.6 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 51.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.8 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 39.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 18.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 98.7 MB/s eta 0:00:00
Downloading torchmetrics-1.7.0-py3-none-any.whl (960 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 960.9/960.9 kB 58.2 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, lightning-utilities, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torchmetrics, pytorch_lightning
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed lightning-utilities-0.14.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 pytorch_lightning-2.5.1 torchmetrics-1.7.0
Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.1-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.39)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 18.0 MB/s eta 0:00:00
Downloading alembic-1.15.1-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.8/231.8 kB 19.5 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.15.1 colorlog-6.9.0 optuna-4.2.1
Collecting optuna-integration[pytorch_lightning]
  Downloading optuna_integration-4.2.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (from optuna-integration[pytorch_lightning]) (4.2.1)
Collecting lightning (from optuna-integration[pytorch_lightning])
  Downloading lightning-2.5.1-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: PyYAML<8.0,>=5.4 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (6.0.2)
Requirement already satisfied: fsspec<2026.0,>=2022.5.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<2026.0,>=2022.5.0->lightning->optuna-integration[pytorch_lightning]) (2025.3.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (0.14.2)
Requirement already satisfied: packaging<25.0,>=20.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (24.2)
Requirement already satisfied: torch<4.0,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (2.6.0+cu124)
Requirement already satisfied: torchmetrics<3.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (1.7.0)
Requirement already satisfied: tqdm<6.0,>=4.57.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (4.67.1)
Requirement already satisfied: typing-extensions<6.0,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (4.12.2)
Requirement already satisfied: pytorch-lightning in /usr/local/lib/python3.11/dist-packages (from lightning->optuna-integration[pytorch_lightning]) (2.5.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna->optuna-integration[pytorch_lightning]) (1.15.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna->optuna-integration[pytorch_lightning]) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna->optuna-integration[pytorch_lightning]) (2.0.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna->optuna-integration[pytorch_lightning]) (2.0.39)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[pytorch_lightning]) (1.1.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<2026.0,>=2022.5.0->lightning->optuna-integration[pytorch_lightning]) (3.11.14)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from lightning-utilities<2.0,>=0.10.0->lightning->optuna-integration[pytorch_lightning]) (75.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[pytorch_lightning]) (3.1.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<4.0,>=2.1.0->lightning->optuna-integration[pytorch_lightning]) (1.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2026.0,>=2022.5.0->lightning->optuna-integration[pytorch_lightning]) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2026.0,>=2022.5.0->lightning->optuna-integration[pytorch_lightning]) (1.3.2)

In [ ]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
# movie_ratings = pd.read_csv('./dataset/ratings.csv')
# movie_ratings_small = pd.read_csv('./dataset/ratings_small.csv')
# movies_metadata = pd.read_csv('./dataset/movies_metadata.csv')

movie_ratings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movie_dataset/ratings.csv')
movie_ratings_small = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movie_dataset/ratings_small.csv')
movies_metadata = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movie_dataset/movies_metadata.csv')

<ipython-input-7-80c1eb9504cb>:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_metadata = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movie_dataset/movies_metadata.csv')

In [8]:
movie_ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [9]:
movies_metadata.drop_duplicates(subset='id',keep='first', inplace=True)

In [10]:
movies_metadata = movies_metadata[movies_metadata['id'].str.isdigit()]
movies_metadata['id'] = movies_metadata['id'].astype('int64')

<ipython-input-10-7420a33fdfa0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_metadata['id'] = movies_metadata['id'].astype('int64')

In [11]:
movies_metadata = movies_metadata.merge(movie_ratings_small, left_on='id', right_on='movieId', how='left')

In [12]:
movies_metadata.dropna(subset='userId', inplace= True)
movies_metadata.drop(columns=['movieId'], inplace=True)

In [13]:
movies_metadata.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'userId', 'rating', 'timestamp'],
      dtype='object')

In [14]:
movies_metadata['genres']

5        [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6        [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
7        [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
8        [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
9        [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
                               ...
87527    [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
87528    [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
87529    [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
87532    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
87576    [{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...
Name: genres, Length: 44989, dtype: object

In [15]:
import json
def extract_genre_names(metadata):
    # 각 리스트에서 'name' 키 값을 추출
    corrected_json_string = metadata.replace("'", '"')
    json_data = json.loads(corrected_json_string)
    a  = [genre['name'] for genre in json_data if 'name' in genre]
    return a

movies_metadata['genres'] = movies_metadata['genres'].apply(lambda x: extract_genre_names(x))

In [16]:
users_stats = movies_metadata.groupby('userId')['rating'].agg(['mean','std','count']).reset_index()
users_stats.columns = ['userId','user_mean_rating','user_rating_std','user_review_count']
movies_metadata = movies_metadata.merge(users_stats, on='userId', how='left')

In [17]:
movies_metadata['release_year'] = pd.to_datetime(movies_metadata['release_date']).dt.year

movie_stats = movies_metadata.groupby('id')['rating'].agg(['mean', 'count']).reset_index()
movie_stats.columns = ['id', 'movie_mean_rating', 'movie_review_count']

movies_metadata = movies_metadata.merge(movie_stats, on='id', how='left')

In [18]:
movies_metadata.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'userId', 'rating', 'timestamp',
       'user_mean_rating', 'user_rating_std', 'user_review_count',
       'release_year', 'movie_mean_rating', 'movie_review_count'],
      dtype='object')

In [19]:
unique_genres = sorted(set(genre for genres in movies_metadata['genres'] for genre in genres))
genre_to_idx = {genre: idx for idx, genre in enumerate(unique_genres)}


# 장르를 숫자로 변환
movies_metadata['genre_ids'] = movies_metadata['genres'].apply(lambda x: [genre_to_idx[genre] for genre in x])

In [20]:
genre_ratings = movies_metadata.explode('genre_ids').groupby(['userId','genre_ids'])['rating'].mean().reset_index()
genre_ratings.columns = ['userId','genre_ids', 'user_preference']

In [21]:
movies_metadata_exploded = movies_metadata.explode('genre_ids')
movies_metadata_exploded.fillna({'genre_ids': 0}, inplace= True)

<ipython-input-21-2d472db91df7>:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  movies_metadata_exploded.fillna({'genre_ids': 0}, inplace= True)

In [22]:
movies_metadata_exploded = movies_metadata_exploded.merge(genre_ratings, on=['userId','genre_ids'], how='left')

In [23]:
movies_metadata_exploded.isnull().sum()

adult                        0
belongs_to_collection    80502
budget                       0
genres                       0
homepage                 81995
id                           0
imdb_id                      0
original_language            0
original_title               0
overview                   150
popularity                   0
poster_path                 42
production_companies         0
production_countries         0
release_date                29
revenue                      0
runtime                      5
spoken_languages             0
status                       3
tagline                  30071
title                        0
video                        0
vote_average                 0
vote_count                   0
userId                       0
rating                       0
timestamp                    0
user_mean_rating             0
user_rating_std              0
user_review_count            0
release_year                29
movie_mean_rating            0
movie_review_count           0
genre_ids                    0
user_preference              1
dtype: int64

In [24]:
movies_metadata_exploded[[ 'user_mean_rating', 'user_rating_std']].isnull().sum()

user_mean_rating    0
user_rating_std     0
dtype: int64

In [25]:
numeric_features_cols = ['user_mean_rating', 'user_rating_std', 'user_review_count',
       'release_year', 'movie_mean_rating', 'movie_review_count', 'genre_ids',
       'user_preference']
movies_metadata_exploded.fillna({'release_year':0}, inplace=True)
movies_metadata_exploded.fillna({'user_preference':0}, inplace=True)
movies_metadata_exploded.fillna({'user_rating_std':0}, inplace= True)

In [26]:
numeric_features_cols = ['user_mean_rating', 'user_rating_std', 'user_review_count',
       'release_year', 'movie_mean_rating', 'movie_review_count', 'genre_ids',
       'user_preference']

scaler = StandardScaler()
movies_metadata_exploded[numeric_features_cols] = scaler.fit_transform(movies_metadata_exploded[numeric_features_cols])

In [27]:
target = ['user_mean_rating', 'user_rating_std', 'user_review_count',
       'release_year', 'movie_mean_rating', 'movie_review_count', 'genre_ids',
       'user_preference','id','userId','rating']
movies_metadata_exploded[target]

,user_mean_rating,user_rating_std,user_review_count,release_year,movie_mean_rating,movie_review_count,genre_ids,user_preference,id,userId,rating
0,0.207586,-0.354892,0.669992,0.217014,0.049479,-0.826605,-1.405291,0.245843,949,23.0,3.5
1,0.207586,-0.354892,0.669992,0.217014,0.049479,-0.826605,-0.686947,0.574224,949,23.0,3.5
2,0.207586,-0.354892,0.669992,0.217014,0.049479,-0.826605,-0.327775,0.149901,949,23.0,3.5
3,0.207586,-0.354892,0.669992,0.217014,0.049479,-0.826605,1.647671,0.354781,949,23.0,3.5
4,0.949350,-0.427886,0.654369,0.217014,0.049479,-0.826605,-1.405291,0.721596,949,102.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...
110073,0.733337,-1.364769,-0.840205,0.659329,0.817022,-1.027519,-0.866533,0.938690,98604,352.0,4.0
110074,0.733337,-1.364769,-0.840205,0.659329,0.817022,-1.027519,1.108913,0.516978,98604,352.0,4.0
110075,0.320610,0.231559,-0.199674,-2.254746,2.706358,-1.027519,0.031397,1.165766,49280,187.0,5.0
110076,0.320610,0.231559,-0.199674,-2.254746,2.706358,-1.027519,-1.405291,0.268912,49280,187.0,5.0
110077,0.320610,0.231559,-0.199674,-2.254746,2.706358,-1.027519,1.647671,0.078608,49280,187.0,5.0

In [29]:
movies_metadata_exploded[target].isnull().sum()

user_mean_rating      0
user_rating_std       0
user_review_count     0
release_year          0
movie_mean_rating     0
movie_review_count    0
genre_ids             0
user_preference       0
id                    0
userId                0
rating                0
dtype: int64

In [32]:
# Neural MF Model
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl

class NeuralMF(pl.LightningModule):
    def __init__(self, num_users, num_items, num_numeric_features, latent_dim, dropout, learning_rate=0.001):
        super(NeuralMF, self).__init__()

        # Embeddings
        self.user_embedding = nn.Embedding(num_users, latent_dim, max_norm=1.0)
        self.item_embedding = nn.Embedding(num_items, latent_dim, max_norm=1.0)
        self.numeric_fc = nn.Linear(num_numeric_features, latent_dim)
        # Neural network layers
        self.gmf_fc = nn.Linear(latent_dim, latent_dim)
        # MLP (Multi-Layer Perceptron)
        self.mlp_fc1 = nn.Linear(latent_dim * 3, 128)
        self.mlp_fc2 = nn.Linear(128, 64)
        self.final_fc = nn.Linear(latent_dim + 64, 1)  # GMF(latent_dim) + MLP(64)
        self.dropout = nn.Dropout(dropout)
        self.activation = nn.ReLU()
        self.learning_rate = learning_rate
        self.criterion = nn.MSELoss()

    def forward(self, user, item, numeric_features):
        user_embed = self.user_embedding(user)
        item_embed = self.item_embedding(item)
        numeric_emb = self.numeric_fc(numeric_features)
        gmf = user_embed * item_embed  # 원소별 곱
        gmf = self.gmf_fc(gmf)  # (batch_size, latent_dim)
        # Concatenate user and item embeddings
        mlp = torch.cat([user_embed, item_embed, numeric_emb], dim=1)
        mlp = self.activation(self.mlp_fc1(mlp))
        mlp = self.dropout(mlp)
        mlp = self.activation(self.mlp_fc2(mlp))  # (batch_size, 64)

        x = torch.cat([gmf, mlp], dim=1)  # (batch_size, latent_dim + 64)
        x = self.final_fc(x)  # (batch_size, 1)
        return (torch.sigmoid(x) * 5).squeeze()

    def training_step(self, batch, batch_idx):
        user_ids, item_ids, numeric_features, ratings = batch
        predicted_ratings = self.forward(user_ids, item_ids, numeric_features)
        train_loss = self.criterion(predicted_ratings, ratings)
        validation_loss = self.trainer.callback_metrics.get("validation_loss", torch.tensor(float('inf'))).item()

        # 🔥 Train과 Validation Loss 차이를 계산
        loss_gap = validation_loss - train_loss.item()

        self.log("loss_gap", loss_gap, prog_bar=True, on_epoch=True, on_step=True)
        # self.log("train_loss", loss, prog_bar=True, on_epoch=True,  on_step = True)  # 🔥 손실 로깅 추가
        return train_loss

    def validation_step(self, batch, batch_idx):
        user_ids, item_ids, numeric_features, ratings = batch
        predicted_ratings = self.forward(user_ids, item_ids, numeric_features)
        loss = self.criterion(predicted_ratings, ratings)
        self.log("validation_loss", loss, prog_bar=True, on_epoch=True, on_step = True)  # 🔥 손실 로깅 추가
        return loss

    def predict_step(self, batch, batch_idx):
        """Lightning에서 `trainer.predict()`를 호출할 때 사용"""
        user, item, numeric_features, ratings = batch  # 배치에서 올바른 입력 추출
        prediction = self.forward(user, item, numeric_features)
        return prediction, ratings

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=self.learning_rate,  weight_decay=1e-3)

In [36]:
from optuna.integration import PyTorchLightningPruningCallback
data = movies_metadata_exploded[target]
train_data, val_data = train_test_split(data, test_size=0.2, random_state=42)
small_train_data = train_data.sample(frac=0.2, random_state=42)
val_data, test_data = train_test_split(val_data, test_size=0.5, random_state=42)  # 검증 & 테스트 분리

def objective(trial):
    latent_dim = trial.suggest_int("latent_dim", 8, 128)  # 8~64 사이 정수
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64,128])  # 16, 32, 64 중 선택
    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-3, log=True)  # log=True 사용
    epochs = trial.suggest_int("epochs", 10, 50)  # 10~50 사이 정수
    num_workers = trial.suggest_int("num_workers", 0, 4)  # 🔥 num_workers도 최적화 가능!
    dropout = trial.suggest_float("dropout", 0.0, 0.7)  # 드롭아웃 비율


    def prepare(data, is_train):
      data['user_idx'] = data['userId'].astype('category').cat.codes
      data['item_idx'] = data['id'].astype('category').cat.codes
      user_ids = torch.tensor(data['user_idx'].values, dtype=torch.long)
      item_ids = torch.tensor(data['item_idx'].values, dtype=torch.long)
      ratings = torch.tensor(data['rating'].values, dtype=torch.float32)
      num_users = data['user_idx'].nunique()
      num_items = data['item_idx'].nunique()
      numeric_features = torch.tensor(data[numeric_features_cols].values, dtype=torch.float32)
      dataset = TensorDataset(user_ids, item_ids, numeric_features, ratings)
      loader = DataLoader(dataset, batch_size=batch_size, shuffle= is_train, num_workers= num_workers)
      return loader, num_users, num_items, numeric_features.shape[1]

    train_loader, num_users, num_items, num_numeric = prepare(small_train_data, True)
    val_loader, _, _, _ = prepare(val_data, False)

    model = NeuralMF(num_users, num_items, num_numeric,  latent_dim, dropout, learning_rate)
    pruning_callback = PyTorchLightningPruningCallback(trial, monitor="loss_gap")
    trainer = pl.Trainer(
        max_epochs=epochs,
        enable_checkpointing=False, # 체크포인트 저장 비활성화
        enable_progress_bar=False, # 진행 바 비활성화
        logger=False # 로그 저장 비활성화
    )
    trainer.callbacks.append(pruning_callback)  # 🔥 여기서 직접 추가
    trainer.fit(model, train_loader, val_loader)
    train_loss = trainer.callback_metrics.get("train_loss", torch.tensor(float('inf'))).item()
    validation_loss = trainer.callback_metrics.get("validation_loss", torch.tensor(float('inf'))).item()
    loss_gap = train_loss - validation_loss  # 🔥 loss_gap을 최종 반환
    # del train_loader
    # del val_loader
    gc.collect()  # 🔥 가비지 컬렉션 실행
    torch.cuda.empty_cache()  # 🔥 GPU 캐시 정리 (GPU 사용 시)
    return loss_gap

# ✅ Optuna 실행
study = optuna.create_study(
        study_name="newMF_study",
        storage="sqlite:///optuna_results.db")  # 최소화 목표: 손실을 최소화하려고 함
study.optimize(objective, n_trials=20)  # n_trials는 실험 횟수

# ✅ 최적 하이퍼파라미터 출력
print("Best Hyperparameters:", study.best_params)

[I 2025-03-25 04:59:30,151] A new study created in RDB with name: newMF_study
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 74.5 K | train
1 | item_embedding | Embedding | 221 K  | train
2 | numeric_fc     | Linear    | 1.0 K  | train
3 | gmf_fc         | Linear    | 12.7 K | train
4 | mlp_fc1        | Linear    | 43.1 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 177    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
361 K     Trainable params
0         Non-trainable params
361 K     Total params
1.445     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
INFO: `Trainer.fit` stopped: `max_epochs=42` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=42` reached.
[I 2025-03-25 05:00:17,698] Trial 0 finished with value: inf and parameters: {'latent_dim': 112, 'batch_size': 128, 'learning_rate': 0.00011357020401617381, 'epochs': 42, 'num_workers': 0, 'dropout': 0.4060787393086205}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 14.6 K | train
1 | item_embedding | Embedding | 43.5 K | train
2 | numeric_fc     | Linear    | 198    | train
3 | gmf_fc         | Linear    | 506    | train
4 | mlp_fc1        | Linear    | 8.6 K  | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 87     | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
75.8 K    Trainable params
0         Non-trainable params
75.8 K    Total params
0.303     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.
[I 2025-03-25 05:01:45,964] Trial 1 finished with value: inf and parameters: {'latent_dim': 22, 'batch_size': 16, 'learning_rate': 0.0005629394996205453, 'epochs': 10, 'num_workers': 1, 'dropout': 0.2517231330828908}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 71.8 K | train
1 | item_embedding | Embedding | 213 K  | train
2 | numeric_fc     | Linear    | 972    | train
3 | gmf_fc         | Linear    | 11.8 K | train
4 | mlp_fc1        | Linear    | 41.6 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 173    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
348 K     Trainable params
0         Non-trainable params
348 K     Total params
1.393     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
INFO: `Trainer.fit` stopped: `max_epochs=16` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=16` reached.
[I 2025-03-25 05:04:11,233] Trial 2 finished with value: inf and parameters: {'latent_dim': 108, 'batch_size': 16, 'learning_rate': 0.0005893541144622249, 'epochs': 16, 'num_workers': 3, 'dropout': 0.5769093497746882}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 26.6 K | train
1 | item_embedding | Embedding | 79.2 K | train
2 | numeric_fc     | Linear    | 360    | train
3 | gmf_fc         | Linear    | 1.6 K  | train
4 | mlp_fc1        | Linear    | 15.5 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 105    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
131 K     Trainable params
0         Non-trainable params
131 K     Total params
0.526     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
INFO: `Trainer.fit` stopped: `max_epochs=35` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=35` reached.
[I 2025-03-25 05:07:47,284] Trial 3 finished with value: inf and parameters: {'latent_dim': 40, 'batch_size': 16, 'learning_rate': 0.0002311563895611429, 'epochs': 35, 'num_workers': 0, 'dropout': 0.6644120008120298}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 62.5 K | train
1 | item_embedding | Embedding | 186 K  | train
2 | numeric_fc     | Linear    | 846    | train
3 | gmf_fc         | Linear    | 8.9 K  | train
4 | mlp_fc1        | Linear    | 36.2 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 159    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
302 K     Trainable params
0         Non-trainable params
302 K     Total params
1.212     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
INFO: `Trainer.fit` stopped: `max_epochs=25` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=25` reached.
[I 2025-03-25 05:08:20,013] Trial 4 finished with value: inf and parameters: {'latent_dim': 94, 'batch_size': 128, 'learning_rate': 0.00021257279477367562, 'epochs': 25, 'num_workers': 1, 'dropout': 0.1692774159736265}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 52.5 K | train
1 | item_embedding | Embedding | 156 K  | train
2 | numeric_fc     | Linear    | 711    | train
3 | gmf_fc         | Linear    | 6.3 K  | train
4 | mlp_fc1        | Linear    | 30.5 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 144    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
254 K     Trainable params
0         Non-trainable params
254 K     Total params
1.019     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
[I 2025-03-25 05:08:22,813] Trial 5 pruned. Trial was pruned at epoch 1.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 11.3 K | train
1 | item_embedding | Embedding | 33.6 K | train
2 | numeric_fc     | Linear    | 153    | train
3 | gmf_fc         | Linear    | 306    | train
4 | mlp_fc1        | Linear    | 6.7 K  | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 82     | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
60.4 K    Trainable params
0         Non-trainable params
60.4 K    Total params
0.242     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
[I 2025-03-25 05:08:25,599] Trial 6 pruned. Trial was pruned at epoch 1.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 71.8 K | train
1 | item_embedding | Embedding | 213 K  | train
2 | numeric_fc     | Linear    | 972    | train
3 | gmf_fc         | Linear    | 11.8 K | train
4 | mlp_fc1        | Linear    | 41.6 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 173    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
348 K     Trainable params
0         Non-trainable params
348 K     Total params
1.393     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
INFO: `Trainer.fit` stopped: `max_epochs=11` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=11` reached.
[I 2025-03-25 05:09:44,222] Trial 7 finished with value: inf and parameters: {'latent_dim': 108, 'batch_size': 16, 'learning_rate': 0.0005298474178024716, 'epochs': 11, 'num_workers': 0, 'dropout': 0.3439750550362751}. Best is trial 0 with value: inf.
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 80.5 K | train
1 | item_embedding | Embedding | 239 K  | train
2 | numeric_fc     | Linear    | 1.1 K  | train
3 | gmf_fc         | Linear    | 14.8 K | train
4 | mlp_fc1        | Linear    | 46.6 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 186    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
390 K     Trainable params
0         Non-trainable params
390 K     Total params
1.563     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/usr/local/lib/python3.11/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

Best Hyperparameters: {'latent_dim': 112, 'batch_size': 128, 'learning_rate': 0.00011357020401617381, 'epochs': 42, 'num_workers': 0, 'dropout': 0.4060787393086205}

In [37]:
print("Best Hyperparameters:", study.best_params)

Best Hyperparameters: {'latent_dim': 112, 'batch_size': 128, 'learning_rate': 0.00011357020401617381, 'epochs': 42, 'num_workers': 0, 'dropout': 0.4060787393086205}

In [38]:
print(f"Number of trials: {len(study.trials)}")
print(f"Completed trials: {[t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]}")

Number of trials: 20
Completed trials: [FrozenTrial(number=0, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 4, 59, 30, 158936), datetime_complete=datetime.datetime(2025, 3, 25, 5, 0, 17, 674872), params={'latent_dim': 112, 'batch_size': 128, 'learning_rate': 0.00011357020401617381, 'epochs': 42, 'num_workers': 0, 'dropout': 0.4060787393086205}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.0009090304374694824, 2: 0.11220228672027588, 3: 0.0691525936126709, 4: -0.2426459789276123, 5: 0.04700970649719238, 6: 0.02738773822784424, 7: 0.07087302207946777, 8: -0.04460674524307251, 9: -0.27453309297561646, 10: 0.0019083023071289062, 11: 0.13027268648147583, 12: 0.12325209379196167, 13: 0.20788320899009705, 14: -0.23681306838989258, 15: -0.08625483512878418, 16: 0.19841599464416504, 17: -0.031978487968444824, 18: -0.020531535148620605, 19: -0.22348660230636597, 20: 0.08323246240615845, 21: 0.1727910041809082, 22: 0.15799438953399658, 23: 0.14650946855545044, 24: 0.2741531431674957, 25: 0.10409575700759888, 26: 0.24269413948059082, 27: 0.06744211912155151, 28: 0.3928930163383484, 29: 0.27268749475479126, 30: 0.2045881748199463, 31: 0.22405004501342773, 32: 0.16941285133361816, 33: 0.13524645566940308, 34: 0.20492839813232422, 35: 0.2699592411518097, 36: 0.1599380373954773, 37: 0.29421892762184143, 38: 0.28866124153137207, 39: 0.23554551601409912, 40: 0.2559299170970917, 41: 0.4788965582847595}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=1, value=None), FrozenTrial(number=1, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 0, 17, 705833), datetime_complete=datetime.datetime(2025, 3, 25, 5, 1, 45, 944058), params={'latent_dim': 22, 'batch_size': 16, 'learning_rate': 0.0005629394996205453, 'epochs': 10, 'num_workers': 1, 'dropout': 0.2517231330828908}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: 0.047018229961395264, 2: -0.23859363794326782, 3: 0.31730252504348755, 4: 0.08916592597961426, 5: 0.3848535418510437, 6: 0.04626452922821045, 7: 0.013508200645446777, 8: 0.3433336913585663, 9: -0.18368816375732422}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=2, value=None), FrozenTrial(number=2, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 1, 45, 971350), datetime_complete=datetime.datetime(2025, 3, 25, 5, 4, 11, 214400), params={'latent_dim': 108, 'batch_size': 16, 'learning_rate': 0.0005893541144622249, 'epochs': 16, 'num_workers': 3, 'dropout': 0.5769093497746882}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.5033029913902283, 2: -0.10181450843811035, 3: 0.019306182861328125, 4: -1.28128182888031, 5: 0.2066941261291504, 6: 0.12326884269714355, 7: -0.023222684860229492, 8: 0.2925235629081726, 9: 0.29048240184783936, 10: 0.0968509316444397, 11: 0.14322441816329956, 12: 0.4279981553554535, 13: 0.4016915559768677, 14: 0.12516731023788452, 15: 0.1865563988685608}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=3, value=None), FrozenTrial(number=3, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 4, 11, 240031), datetime_complete=datetime.datetime(2025, 3, 25, 5, 7, 47, 267730), params={'latent_dim': 40, 'batch_size': 16, 'learning_rate': 0.0002311563895611429, 'epochs': 35, 'num_workers': 0, 'dropout': 0.6644120008120298}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.43899834156036377, 2: 0.443236768245697, 3: -0.25891077518463135, 4: 0.2829618752002716, 5: -0.3308001756668091, 6: -0.3762325048446655, 7: 0.35171422362327576, 8: 0.028819680213928223, 9: 0.42359092831611633, 10: -0.03286868333816528, 11: 0.10917752981185913, 12: -0.5330084562301636, 13: 0.2880646884441376, 14: -0.024190843105316162, 15: 0.21572190523147583, 16: 0.6233526468276978, 17: 0.05153936147689819, 18: 0.07324540615081787, 19: 0.4495769739151001, 20: -0.33384770154953003, 21: 0.5201518535614014, 22: 0.5099084377288818, 23: 0.17236953973770142, 24: 0.3086904287338257, 25: 0.23740160465240479, 26: 0.2499157190322876, 27: 0.17125612497329712, 28: 0.3930353820323944, 29: 0.3649095892906189, 30: 0.14957207441329956, 31: 0.3203849494457245, 32: -0.1788058876991272, 33: 0.440104216337204, 34: -0.007779538631439209}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=4, value=None), FrozenTrial(number=4, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 7, 47, 291473), datetime_complete=datetime.datetime(2025, 3, 25, 5, 8, 19, 994722), params={'latent_dim': 94, 'batch_size': 128, 'learning_rate': 0.00021257279477367562, 'epochs': 25, 'num_workers': 1, 'dropout': 0.1692774159736265}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.015181779861450195, 2: 0.16650497913360596, 3: 0.12093532085418701, 4: 0.08535069227218628, 5: -0.23402166366577148, 6: 0.05758786201477051, 7: 0.12467831373214722, 8: 0.009547591209411621, 9: 0.21500495076179504, 10: 0.2069503664970398, 11: 0.16445022821426392, 12: 0.22815179824829102, 13: 0.11910754442214966, 14: -0.042450547218322754, 15: 0.06477034091949463, 16: 0.05122309923171997, 17: 0.20671498775482178, 18: 0.1544560194015503, 19: 0.2710268497467041, 20: 0.04529958963394165, 21: 0.23197013139724731, 22: 0.13491809368133545, 23: 0.3279248774051666, 24: 0.36436396837234497}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=5, value=None), FrozenTrial(number=7, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 8, 25, 607243), datetime_complete=datetime.datetime(2025, 3, 25, 5, 9, 44, 198338), params={'latent_dim': 108, 'batch_size': 16, 'learning_rate': 0.0005298474178024716, 'epochs': 11, 'num_workers': 0, 'dropout': 0.3439750550362751}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.15421879291534424, 2: -0.19851362705230713, 3: 0.08787435293197632, 4: -0.4491957426071167, 5: 0.4067445397377014, 6: -0.3095722794532776, 7: -0.17362302541732788, 8: -0.05358368158340454, 9: -0.044394612312316895, 10: 0.2806178033351898}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=8, value=None), FrozenTrial(number=9, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 9, 48, 29897), datetime_complete=datetime.datetime(2025, 3, 25, 5, 10, 21, 130747), params={'latent_dim': 22, 'batch_size': 128, 'learning_rate': 0.0008877253288149641, 'epochs': 29, 'num_workers': 0, 'dropout': 0.18901079880006535}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.25922882556915283, 2: 0.034676969051361084, 3: -0.00018835067749023438, 4: 0.19467389583587646, 5: -0.10452151298522949, 6: 0.13952702283859253, 7: 0.1899477243423462, 8: 0.19319918751716614, 9: 0.15705859661102295, 10: 0.20234403014183044, 11: 0.009006500244140625, 12: 0.13889187574386597, 13: 0.26108095049858093, 14: 0.1443246603012085, 15: 0.12417900562286377, 16: 0.1139799952507019, 17: 0.21716976165771484, 18: 0.42247503995895386, 19: 0.4674317538738251, 20: 0.44283515214920044, 21: 0.5173652172088623, 22: 0.43621203303337097, 23: 0.5303978323936462, 24: 0.5322560667991638, 25: 0.48269936442375183, 26: 0.5629475712776184, 27: 0.6045315265655518, 28: 0.613028347492218}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=10, value=None), FrozenTrial(number=16, state=1, values=[inf], datetime_start=datetime.datetime(2025, 3, 25, 5, 11, 35, 140612), datetime_complete=datetime.datetime(2025, 3, 25, 5, 15, 58, 903483), params={'latent_dim': 84, 'batch_size': 32, 'learning_rate': 0.00029379763704413326, 'epochs': 49, 'num_workers': 3, 'dropout': 0.2841989718862743}, user_attrs={}, system_attrs={}, intermediate_values={0: inf, 1: -0.2423117756843567, 2: 0.2613915205001831, 3: 0.3474270701408386, 4: 0.13243317604064941, 5: -0.3478395938873291, 6: 0.16545069217681885, 7: 0.28913038969039917, 8: 0.5919808745384216, 9: 0.10405075550079346, 10: 0.2883877158164978, 11: 0.3642793893814087, 12: 0.30465736985206604, 13: 0.31122875213623047, 14: 0.3253956437110901, 15: 0.35702717304229736, 16: 0.18789517879486084, 17: 0.134177565574646, 18: 0.18132376670837402, 19: -0.5061174631118774, 20: 0.07953113317489624, 21: 0.1573868989944458, 22: -0.5259882211685181, 23: 0.6196557879447937, 24: 0.40396806597709656, 25: 0.42506060004234314, 26: 0.1007508635520935, 27: 0.6687597632408142, 28: -0.17274653911590576, 29: 0.3815320134162903, 30: 0.49947044253349304, 31: 0.20674622058868408, 32: 0.6736817955970764, 33: 0.6856686472892761, 34: 0.5832258462905884, 35: -0.0745953917503357, 36: 0.6796491742134094, 37: 0.3820533752441406, 38: 0.371834397315979, 39: 0.5456128120422363, 40: 0.7241930365562439, 41: 0.7556555271148682, 42: 0.7530139684677124, 43: 0.6720536947250366, 44: 0.5073468685150146, 45: 0.6995105743408203, 46: 0.8320263624191284, 47: 0.7887079119682312, 48: 0.8186999559402466}, distributions={'latent_dim': IntDistribution(high=128, log=False, low=8, step=1), 'batch_size': CategoricalDistribution(choices=(16, 32, 64, 128)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0001, step=None), 'epochs': IntDistribution(high=50, log=False, low=10, step=1), 'num_workers': IntDistribution(high=4, log=False, low=0, step=1), 'dropout': FloatDistribution(high=0.7, log=False, low=0.0, step=None)}, trial_id=17, value=None)]

In [54]:
#Best Hyperparameters: {'latent_dim': 43, 'batch_size': 32, 'learning_rate': 0.000532381383106112, 'epochs': 11, 'num_workers': 1}

#best_params = study.best_params

data = movies_metadata_exploded[target]
train_data, val_data = train_test_split(data, test_size=0.2, random_state=42)
small_train_data = train_data.sample(frac=0.2, random_state=42)
val_data, test_data = train_test_split(val_data, test_size=0.5, random_state=42)  # 검증 & 테스트 분리

#best_params =  {'latent_dim': 24, 'batch_size': 16, 'learning_rate': 0.00010468856330302876, 'epochs': 24, 'num_workers': 3,  'dropout': 0.47353989106173777}
best_params = {
    'latent_dim': 112,
    'batch_size': 128,
    'learning_rate': 0.00011357020401617381,
    'epochs': 42,
    'num_workers': 0,
    'dropout': 0.4060787393086205
}
latent_dim = best_params['latent_dim']
batch_size = best_params['batch_size']
learning_rate = best_params['learning_rate']
epochs = best_params['epochs']
num_workers = best_params['num_workers']
dropout = best_params['dropout']


def prepare(data, is_train):
    data['user_idx'] = data['userId'].astype('category').cat.codes
    data['item_idx'] = data['id'].astype('category').cat.codes
    user_ids = torch.tensor(data['user_idx'].values, dtype=torch.long)
    item_ids = torch.tensor(data['item_idx'].values, dtype=torch.long)
    ratings = torch.tensor(data['rating'].values, dtype=torch.float32)
    num_users = data['user_idx'].nunique()
    num_items = data['item_idx'].nunique()
    numeric_features = torch.tensor(data[numeric_features_cols].values, dtype=torch.float32)
    dataset = TensorDataset(user_ids, item_ids, numeric_features, ratings)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle= is_train, num_workers= 2)
    return loader, num_users, num_items, numeric_features.shape[1]

train_loader, num_users, num_items, num_numeric = prepare(train_data, True)
val_loader, _, _, _ = prepare(val_data, False)

model = NeuralMF(num_users, num_items, num_numeric, latent_dim, dropout, learning_rate)
trainer = pl.Trainer(
    max_epochs=epochs,
    enable_checkpointing=False, # 체크포인트 저장 비활성화
    enable_progress_bar=False, # 진행 바 비활성화
    logger=False # 로그 저장 비활성화
)
trainer.fit(model, train_loader, val_loader)

# 모델 학습이 끝난 후 불필요한 변수 제거
#del train_loader, val_loader
torch.cuda.empty_cache()  # GPU 메모리 해제
gc.collect()  # Python 가비지 컬렉션 실행

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name           | Type      | Params | Mode
-----------------------------------------------------
0 | user_embedding | Embedding | 75.2 K | train
1 | item_embedding | Embedding | 311 K  | train
2 | numeric_fc     | Linear    | 1.0 K  | train
3 | gmf_fc         | Linear    | 12.7 K | train
4 | mlp_fc1        | Linear    | 43.1 K | train
5 | mlp_fc2        | Linear    | 8.3 K  | train
6 | final_fc       | Linear    | 177    | train
7 | dropout        | Dropout   | 0      | train
8 | activation     | ReLU      | 0      | train
9 | criterion      | MSELoss   | 0      | train
-----------------------------------------------------
451 K     Trainable params
0         Non-trainable params
451 K     Total params
1.807     Total estimated model params size (MB)
10        Modules in train mode
0         Modules in eval mode
INFO: `Trainer.fit` stopped: `max_epochs=42` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=42` reached.

775

In [55]:
test_loader, _, _, _ = prepare(test_data, False)
predictions = trainer.predict(model, test_loader)

INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

In [129]:
for user_ids, item_ids, numeric_features, ratings in test_loader:
  print(user_ids.shape)
  print(item_ids.shape)
  print(numeric_features.shape)
  print(ratings.shape)
  break

torch.Size([128])
torch.Size([128])
torch.Size([128, 8])
torch.Size([128])

In [85]:
num_users,  num_items

(671, 2779)

In [41]:
predicted_ratings = []
actual_ratings = []
for pred, rating in predictions:
    predicted_ratings.append(pred)
    actual_ratings.append(rating)

In [44]:
# ✅ MSE 계산 (sklearn)
mse = mean_squared_error(actual_ratings, predicted_ratings)
print(f"Test MSE: {mse}")

Test MSE: 0.8107448788708513

In [45]:
mae = mean_absolute_error(actual_ratings, predicted_ratings)
print(f"Test MAE: {mae}")

Test MAE: 0.6894948442769777

In [46]:
#RMSE 계산
rmse = np.sqrt(mse)
print(f"Test RMSE: {rmse}")

Test RMSE: 0.9004137265006855

In [76]:
torch.save(model.state_dict(), "best_model.pth")

In [116]:
# 유저 1의 user_idx 찾기
user_id = 2
item_title = "장화, 홍련"
item_id = int(movies_metadata_exploded[movies_metadata_exploded['original_title'] == item_title]['id'].iloc[0])

user_idx = train_data[train_data['userId'] == user_id]['user_idx'].unique()[0]
item_idx = train_data[train_data['id'] == item_id]['item_idx'].unique()[0]

print(f"유저 {user_id} user_index: {user_idx}, {item_id} item_index: {item_idx}")

numeric_item_features = train_data[train_data['item_idx'] == item_idx][numeric_features_cols]

numeric_item_features.mean().values

유저 2 user_index: 1, 4552 item_index: 1596

array([ 0.14000068,  0.22755207, -0.17710736,  0.42516245,  1.0531892 ,
       -0.9873358 ,  0.53024706, -0.20964886])

In [ ]:
user_ids = torch.tensor([user_idx], dtype=torch.long)  # 예: 사용자 아이디
item_ids = torch.tensor([item_idx], dtype=torch.long)  # 예: 아이템 아이디
numeric_features = torch.tensor(numeric_item_features.mean().values,  dtype=torch.float32)  # 예: 숫자형 특성 (예: 나이, 성별, 등)
item_features = numeric_features.reshape(1, -1)
# 모델을 통해 예측 수행
predicted_rating = model(user_ids, item_ids, item_features)
# 예측된 평점 출력
print(predicted_rating.item())

4.16526460647583